repos:
  - repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: ["--select=E9,F63,F7,F82", "--count"]

